import {cj} from "./engine"

export const bj_PI = 3.14159265358979323846
export const bj_E = 2.71828182845904523536
export const bj_CELLWIDTH = 128.0
export const bj_CLIFFHEIGHT = 128.0
export const bj_UNIT_FACING = 270.0
export const bj_RADTODEG = 180.0 / bj_PI
export const bj_DEGTORAD = bj_PI / 180.0
export const bj_TEXT_DELAY_QUEST = 20.00
export const bj_TEXT_DELAY_QUESTUPDATE = 20.00
export const bj_TEXT_DELAY_QUESTDONE = 20.00
export const bj_TEXT_DELAY_QUESTFAILED = 20.00
export const bj_TEXT_DELAY_QUESTREQUIREMENT = 20.00
export const bj_TEXT_DELAY_MISSIONFAILED = 20.00
export const bj_TEXT_DELAY_ALWAYSHINT = 12.00
export const bj_TEXT_DELAY_HINT = 12.00
export const bj_TEXT_DELAY_SECRET = 10.00
export const bj_TEXT_DELAY_UNITACQUIRED = 15.00
export const bj_TEXT_DELAY_UNITAVAILABLE = 10.00
export const bj_TEXT_DELAY_ITEMACQUIRED = 10.00
export const bj_TEXT_DELAY_WARNING = 12.00
export const bj_QUEUE_DELAY_QUEST = 5.00
export const bj_QUEUE_DELAY_HINT = 5.00
export const bj_QUEUE_DELAY_SECRET = 3.00
export const bj_HANDICAP_EASY = 60.00
export const bj_GAME_STARTED_THRESHOLD = 0.01
export const bj_WAIT_FOR_COND_MIN_INTERVAL = 0.10
export const bj_POLLED_WAIT_INTERVAL = 0.10
export const bj_POLLED_WAIT_SKIP_THRESHOLD = 2.00
export const bj_MAX_INVENTORY = 6
export const bj_MAX_PLAYERS = 12
export const bj_PLAYER_NEUTRAL_VICTIM = 13
export const bj_PLAYER_NEUTRAL_EXTRA = 14
export const bj_MAX_PLAYER_SLOTS = 16
export const bj_MAX_SKELETONS = 25
export const bj_MAX_STOCK_ITEM_SLOTS = 11
export const bj_MAX_STOCK_UNIT_SLOTS = 11
export const bj_MAX_ITEM_LEVEL = 10
export const bj_TOD_DAWN = 6.00
export const bj_TOD_DUSK = 18.00
export const bj_MELEE_STARTING_TOD = 8.00
export const bj_MELEE_STARTING_GOLD_V0 = 750
export const bj_MELEE_STARTING_GOLD_V1 = 500
export const bj_MELEE_STARTING_LUMBER_V0 = 200
export const bj_MELEE_STARTING_LUMBER_V1 = 150
export const bj_MELEE_STARTING_HERO_TOKENS = 1
export const bj_MELEE_HERO_LIMIT = 3
export const bj_MELEE_HERO_TYPE_LIMIT = 1
export const bj_MELEE_MINE_SEARCH_RADIUS = 2000
export const bj_MELEE_CLEAR_UNITS_RADIUS = 1500
export const bj_MELEE_CRIPPLE_TIMEOUT = 120.00
export const bj_MELEE_CRIPPLE_MSG_DURATION = 20.00
export const bj_MELEE_MAX_TWINKED_HEROES_V0 = 3
export const bj_MELEE_MAX_TWINKED_HEROES_V1 = 1
export const bj_CREEP_ITEM_DELAY = 0.50
export const bj_STOCK_RESTOCK_INITIAL_DELAY = 120
export const bj_STOCK_RESTOCK_INTERVAL = 30
export const bj_STOCK_MAX_ITERATIONS = 20
export const bj_MAX_DEST_IN_REGION_EVENTS = 64
export const bj_CAMERA_MIN_FARZ = 100
export const bj_CAMERA_DEFAULT_DISTANCE = 1650
export const bj_CAMERA_DEFAULT_FARZ = 5000
export const bj_CAMERA_DEFAULT_AOA = 304
export const bj_CAMERA_DEFAULT_FOV = 70
export const bj_CAMERA_DEFAULT_ROLL = 0
export const bj_CAMERA_DEFAULT_ROTATION = 90
export const bj_RESCUE_PING_TIME = 2.00
export const bj_NOTHING_SOUND_DURATION = 5.00
export const bj_TRANSMISSION_PING_TIME = 1.00
export const bj_TRANSMISSION_IND_RED = 255
export const bj_TRANSMISSION_IND_BLUE = 255
export const bj_TRANSMISSION_IND_GREEN = 255
export const bj_TRANSMISSION_IND_ALPHA = 255
export const bj_TRANSMISSION_PORT_HANGTIME = 1.50
export const bj_CINEMODE_INTERFACEFADE = 0.50
export const MAP_SPEED_NORMAL = cj.ConvertGameSpeed(2)
export const bj_CINEMODE_GAMESPEED = MAP_SPEED_NORMAL
export const bj_CINEMODE_VOLUME_UNITMOVEMENT = 0.40
export const bj_CINEMODE_VOLUME_UNITSOUNDS = 0.00
export const bj_CINEMODE_VOLUME_COMBAT = 0.40
export const bj_CINEMODE_VOLUME_SPELLS = 0.40
export const bj_CINEMODE_VOLUME_UI = 0.00
export const bj_CINEMODE_VOLUME_MUSIC = 0.55
export const bj_CINEMODE_VOLUME_AMBIENTSOUNDS = 1.00
export const bj_CINEMODE_VOLUME_FIRE = 0.60
export const bj_SPEECH_VOLUME_UNITMOVEMENT = 0.25
export const bj_SPEECH_VOLUME_UNITSOUNDS = 0.00
export const bj_SPEECH_VOLUME_COMBAT = 0.25
export const bj_SPEECH_VOLUME_SPELLS = 0.25
export const bj_SPEECH_VOLUME_UI = 0.00
export const bj_SPEECH_VOLUME_MUSIC = 0.55
export const bj_SPEECH_VOLUME_AMBIENTSOUNDS = 1.00
export const bj_SPEECH_VOLUME_FIRE = 0.60
export const bj_SMARTPAN_TRESHOLD_PAN = 500
export const bj_SMARTPAN_TRESHOLD_SNAP = 3500
export const bj_MAX_QUEUED_TRIGGERS = 100
export const bj_QUEUED_TRIGGER_TIMEOUT = 180.00
export const bj_CAMPAIGN_INDEX_T = 0
export const bj_CAMPAIGN_INDEX_H = 1
export const bj_CAMPAIGN_INDEX_U = 2
export const bj_CAMPAIGN_INDEX_O = 3
export const bj_CAMPAIGN_INDEX_N = 4
export const bj_CAMPAIGN_INDEX_XN = 5
export const bj_CAMPAIGN_INDEX_XH = 6
export const bj_CAMPAIGN_INDEX_XU = 7
export const bj_CAMPAIGN_INDEX_XO = 8
export const bj_CAMPAIGN_OFFSET_T = 0
export const bj_CAMPAIGN_OFFSET_H = 1
export const bj_CAMPAIGN_OFFSET_U = 2
export const bj_CAMPAIGN_OFFSET_O = 3
export const bj_CAMPAIGN_OFFSET_N = 4
export const bj_CAMPAIGN_OFFSET_XN = 0
export const bj_CAMPAIGN_OFFSET_XH = 1
export const bj_CAMPAIGN_OFFSET_XU = 2
export const bj_CAMPAIGN_OFFSET_XO = 3
export const bj_MISSION_INDEX_T00 = bj_CAMPAIGN_OFFSET_T * 1000 + 0
export const bj_MISSION_INDEX_T01 = bj_CAMPAIGN_OFFSET_T * 1000 + 1
export const bj_MISSION_INDEX_H00 = bj_CAMPAIGN_OFFSET_H * 1000 + 0
export const bj_MISSION_INDEX_H01 = bj_CAMPAIGN_OFFSET_H * 1000 + 1
export const bj_MISSION_INDEX_H02 = bj_CAMPAIGN_OFFSET_H * 1000 + 2
export const bj_MISSION_INDEX_H03 = bj_CAMPAIGN_OFFSET_H * 1000 + 3
export const bj_MISSION_INDEX_H04 = bj_CAMPAIGN_OFFSET_H * 1000 + 4
export const bj_MISSION_INDEX_H05 = bj_CAMPAIGN_OFFSET_H * 1000 + 5
export const bj_MISSION_INDEX_H06 = bj_CAMPAIGN_OFFSET_H * 1000 + 6
export const bj_MISSION_INDEX_H07 = bj_CAMPAIGN_OFFSET_H * 1000 + 7
export const bj_MISSION_INDEX_H08 = bj_CAMPAIGN_OFFSET_H * 1000 + 8
export const bj_MISSION_INDEX_H09 = bj_CAMPAIGN_OFFSET_H * 1000 + 9
export const bj_MISSION_INDEX_H10 = bj_CAMPAIGN_OFFSET_H * 1000 + 10
export const bj_MISSION_INDEX_H11 = bj_CAMPAIGN_OFFSET_H * 1000 + 11
export const bj_MISSION_INDEX_U00 = bj_CAMPAIGN_OFFSET_U * 1000 + 0
export const bj_MISSION_INDEX_U01 = bj_CAMPAIGN_OFFSET_U * 1000 + 1
export const bj_MISSION_INDEX_U02 = bj_CAMPAIGN_OFFSET_U * 1000 + 2
export const bj_MISSION_INDEX_U03 = bj_CAMPAIGN_OFFSET_U * 1000 + 3
export const bj_MISSION_INDEX_U05 = bj_CAMPAIGN_OFFSET_U * 1000 + 4
export const bj_MISSION_INDEX_U07 = bj_CAMPAIGN_OFFSET_U * 1000 + 5
export const bj_MISSION_INDEX_U08 = bj_CAMPAIGN_OFFSET_U * 1000 + 6
export const bj_MISSION_INDEX_U09 = bj_CAMPAIGN_OFFSET_U * 1000 + 7
export const bj_MISSION_INDEX_U10 = bj_CAMPAIGN_OFFSET_U * 1000 + 8
export const bj_MISSION_INDEX_U11 = bj_CAMPAIGN_OFFSET_U * 1000 + 9
export const bj_MISSION_INDEX_O00 = bj_CAMPAIGN_OFFSET_O * 1000 + 0
export const bj_MISSION_INDEX_O01 = bj_CAMPAIGN_OFFSET_O * 1000 + 1
export const bj_MISSION_INDEX_O02 = bj_CAMPAIGN_OFFSET_O * 1000 + 2
export const bj_MISSION_INDEX_O03 = bj_CAMPAIGN_OFFSET_O * 1000 + 3
export const bj_MISSION_INDEX_O04 = bj_CAMPAIGN_OFFSET_O * 1000 + 4
export const bj_MISSION_INDEX_O05 = bj_CAMPAIGN_OFFSET_O * 1000 + 5
export const bj_MISSION_INDEX_O06 = bj_CAMPAIGN_OFFSET_O * 1000 + 6
export const bj_MISSION_INDEX_O07 = bj_CAMPAIGN_OFFSET_O * 1000 + 7
export const bj_MISSION_INDEX_O08 = bj_CAMPAIGN_OFFSET_O * 1000 + 8
export const bj_MISSION_INDEX_O09 = bj_CAMPAIGN_OFFSET_O * 1000 + 9
export const bj_MISSION_INDEX_O10 = bj_CAMPAIGN_OFFSET_O * 1000 + 10
export const bj_MISSION_INDEX_N00 = bj_CAMPAIGN_OFFSET_N * 1000 + 0
export const bj_MISSION_INDEX_N01 = bj_CAMPAIGN_OFFSET_N * 1000 + 1
export const bj_MISSION_INDEX_N02 = bj_CAMPAIGN_OFFSET_N * 1000 + 2
export const bj_MISSION_INDEX_N03 = bj_CAMPAIGN_OFFSET_N * 1000 + 3
export const bj_MISSION_INDEX_N04 = bj_CAMPAIGN_OFFSET_N * 1000 + 4
export const bj_MISSION_INDEX_N05 = bj_CAMPAIGN_OFFSET_N * 1000 + 5
export const bj_MISSION_INDEX_N06 = bj_CAMPAIGN_OFFSET_N * 1000 + 6
export const bj_MISSION_INDEX_N07 = bj_CAMPAIGN_OFFSET_N * 1000 + 7
export const bj_MISSION_INDEX_N08 = bj_CAMPAIGN_OFFSET_N * 1000 + 8
export const bj_MISSION_INDEX_N09 = bj_CAMPAIGN_OFFSET_N * 1000 + 9
export const bj_MISSION_INDEX_XN00 = bj_CAMPAIGN_OFFSET_XN * 1000 + 0
export const bj_MISSION_INDEX_XN01 = bj_CAMPAIGN_OFFSET_XN * 1000 + 1
export const bj_MISSION_INDEX_XN02 = bj_CAMPAIGN_OFFSET_XN * 1000 + 2
export const bj_MISSION_INDEX_XN03 = bj_CAMPAIGN_OFFSET_XN * 1000 + 3
export const bj_MISSION_INDEX_XN04 = bj_CAMPAIGN_OFFSET_XN * 1000 + 4
export const bj_MISSION_INDEX_XN05 = bj_CAMPAIGN_OFFSET_XN * 1000 + 5
export const bj_MISSION_INDEX_XN06 = bj_CAMPAIGN_OFFSET_XN * 1000 + 6
export const bj_MISSION_INDEX_XN07 = bj_CAMPAIGN_OFFSET_XN * 1000 + 7
export const bj_MISSION_INDEX_XN08 = bj_CAMPAIGN_OFFSET_XN * 1000 + 8
export const bj_MISSION_INDEX_XN09 = bj_CAMPAIGN_OFFSET_XN * 1000 + 9
export const bj_MISSION_INDEX_XN10 = bj_CAMPAIGN_OFFSET_XN * 1000 + 10
export const bj_MISSION_INDEX_XH00 = bj_CAMPAIGN_OFFSET_XH * 1000 + 0
export const bj_MISSION_INDEX_XH01 = bj_CAMPAIGN_OFFSET_XH * 1000 + 1
export const bj_MISSION_INDEX_XH02 = bj_CAMPAIGN_OFFSET_XH * 1000 + 2
export const bj_MISSION_INDEX_XH03 = bj_CAMPAIGN_OFFSET_XH * 1000 + 3
export const bj_MISSION_INDEX_XH04 = bj_CAMPAIGN_OFFSET_XH * 1000 + 4
export const bj_MISSION_INDEX_XH05 = bj_CAMPAIGN_OFFSET_XH * 1000 + 5
export const bj_MISSION_INDEX_XH06 = bj_CAMPAIGN_OFFSET_XH * 1000 + 6
export const bj_MISSION_INDEX_XH07 = bj_CAMPAIGN_OFFSET_XH * 1000 + 7
export const bj_MISSION_INDEX_XH08 = bj_CAMPAIGN_OFFSET_XH * 1000 + 8
export const bj_MISSION_INDEX_XH09 = bj_CAMPAIGN_OFFSET_XH * 1000 + 9
export const bj_MISSION_INDEX_XU00 = bj_CAMPAIGN_OFFSET_XU * 1000 + 0
export const bj_MISSION_INDEX_XU01 = bj_CAMPAIGN_OFFSET_XU * 1000 + 1
export const bj_MISSION_INDEX_XU02 = bj_CAMPAIGN_OFFSET_XU * 1000 + 2
export const bj_MISSION_INDEX_XU03 = bj_CAMPAIGN_OFFSET_XU * 1000 + 3
export const bj_MISSION_INDEX_XU04 = bj_CAMPAIGN_OFFSET_XU * 1000 + 4
export const bj_MISSION_INDEX_XU05 = bj_CAMPAIGN_OFFSET_XU * 1000 + 5
export const bj_MISSION_INDEX_XU06 = bj_CAMPAIGN_OFFSET_XU * 1000 + 6
export const bj_MISSION_INDEX_XU07 = bj_CAMPAIGN_OFFSET_XU * 1000 + 7
export const bj_MISSION_INDEX_XU08 = bj_CAMPAIGN_OFFSET_XU * 1000 + 8
export const bj_MISSION_INDEX_XU09 = bj_CAMPAIGN_OFFSET_XU * 1000 + 9
export const bj_MISSION_INDEX_XU10 = bj_CAMPAIGN_OFFSET_XU * 1000 + 10
export const bj_MISSION_INDEX_XU11 = bj_CAMPAIGN_OFFSET_XU * 1000 + 11
export const bj_MISSION_INDEX_XU12 = bj_CAMPAIGN_OFFSET_XU * 1000 + 12
export const bj_MISSION_INDEX_XU13 = bj_CAMPAIGN_OFFSET_XU * 1000 + 13
export const bj_MISSION_INDEX_XO00 = bj_CAMPAIGN_OFFSET_XO * 1000 + 0
export const bj_CINEMATICINDEX_TOP = 0
export const bj_CINEMATICINDEX_HOP = 1
export const bj_CINEMATICINDEX_HED = 2
export const bj_CINEMATICINDEX_OOP = 3
export const bj_CINEMATICINDEX_OED = 4
export const bj_CINEMATICINDEX_UOP = 5
export const bj_CINEMATICINDEX_UED = 6
export const bj_CINEMATICINDEX_NOP = 7
export const bj_CINEMATICINDEX_NED = 8
export const bj_CINEMATICINDEX_XOP = 9
export const bj_CINEMATICINDEX_XED = 10
export const bj_ALLIANCE_UNALLIED = 0
export const bj_ALLIANCE_UNALLIED_VISION = 1
export const bj_ALLIANCE_ALLIED = 2
export const bj_ALLIANCE_ALLIED_VISION = 3
export const bj_ALLIANCE_ALLIED_UNITS = 4
export const bj_ALLIANCE_ALLIED_ADVUNITS = 5
export const bj_ALLIANCE_NEUTRAL = 6
export const bj_ALLIANCE_NEUTRAL_VISION = 7
export const bj_KEYEVENTTYPE_DEPRESS = 0
export const bj_KEYEVENTTYPE_RELEASE = 1
export const bj_KEYEVENTKEY_LEFT = 0
export const bj_KEYEVENTKEY_RIGHT = 1
export const bj_KEYEVENTKEY_DOWN = 2
export const bj_KEYEVENTKEY_UP = 3
export const bj_TIMETYPE_ADD = 0
export const bj_TIMETYPE_SET = 1
export const bj_TIMETYPE_SUB = 2
export const bj_CAMERABOUNDS_ADJUST_ADD = 0
export const bj_CAMERABOUNDS_ADJUST_SUB = 1
export const bj_QUESTTYPE_REQ_DISCOVERED = 0
export const bj_QUESTTYPE_REQ_UNDISCOVERED = 1
export const bj_QUESTTYPE_OPT_DISCOVERED = 2
export const bj_QUESTTYPE_OPT_UNDISCOVERED = 3
export const bj_QUESTMESSAGE_DISCOVERED = 0
export const bj_QUESTMESSAGE_UPDATED = 1
export const bj_QUESTMESSAGE_COMPLETED = 2
export const bj_QUESTMESSAGE_FAILED = 3
export const bj_QUESTMESSAGE_REQUIREMENT = 4
export const bj_QUESTMESSAGE_MISSIONFAILED = 5
export const bj_QUESTMESSAGE_ALWAYSHINT = 6
export const bj_QUESTMESSAGE_HINT = 7
export const bj_QUESTMESSAGE_SECRET = 8
export const bj_QUESTMESSAGE_UNITACQUIRED = 9
export const bj_QUESTMESSAGE_UNITAVAILABLE = 10
export const bj_QUESTMESSAGE_ITEMACQUIRED = 11
export const bj_QUESTMESSAGE_WARNING = 12
export const bj_SORTTYPE_SORTBYVALUE = 0
export const bj_SORTTYPE_SORTBYPLAYER = 1
export const bj_SORTTYPE_SORTBYLABEL = 2
export const bj_CINEFADETYPE_FADEIN = 0
export const bj_CINEFADETYPE_FADEOUT = 1
export const bj_CINEFADETYPE_FADEOUTIN = 2
export const bj_REMOVEBUFFS_POSITIVE = 0
export const bj_REMOVEBUFFS_NEGATIVE = 1
export const bj_REMOVEBUFFS_ALL = 2
export const bj_REMOVEBUFFS_NONTLIFE = 3
export const bj_BUFF_POLARITY_POSITIVE = 0
export const bj_BUFF_POLARITY_NEGATIVE = 1
export const bj_BUFF_POLARITY_EITHER = 2
export const bj_BUFF_RESIST_MAGIC = 0
export const bj_BUFF_RESIST_PHYSICAL = 1
export const bj_BUFF_RESIST_EITHER = 2
export const bj_BUFF_RESIST_BOTH = 3
export const bj_HEROSTAT_STR = 0
export const bj_HEROSTAT_AGI = 1
export const bj_HEROSTAT_INT = 2
export const bj_MODIFYMETHOD_ADD = 0
export const bj_MODIFYMETHOD_SUB = 1
export const bj_MODIFYMETHOD_SET = 2
export const bj_UNIT_STATE_METHOD_ABSOLUTE = 0
export const bj_UNIT_STATE_METHOD_RELATIVE = 1
export const bj_UNIT_STATE_METHOD_DEFAULTS = 2
export const bj_UNIT_STATE_METHOD_MAXIMUM = 3
export const bj_GATEOPERATION_CLOSE = 0
export const bj_GATEOPERATION_OPEN = 1
export const bj_GATEOPERATION_DESTROY = 2
export const bj_GAMECACHE_BOOLEAN = 0
export const bj_GAMECACHE_INTEGER = 1
export const bj_GAMECACHE_REAL = 2
export const bj_GAMECACHE_UNIT = 3
export const bj_GAMECACHE_STRING = 4
export const bj_ITEM_STATUS_HIDDEN = 0
export const bj_ITEM_STATUS_OWNED = 1
export const bj_ITEM_STATUS_INVULNERABLE = 2
export const bj_ITEM_STATUS_POWERUP = 3
export const bj_ITEM_STATUS_SELLABLE = 4
export const bj_ITEM_STATUS_PAWNABLE = 5
export const bj_ITEMCODE_STATUS_POWERUP = 0
export const bj_ITEMCODE_STATUS_SELLABLE = 1
export const bj_ITEMCODE_STATUS_PAWNABLE = 2
export const bj_MINIMAPPINGSTYLE_SIMPLE = 0
export const bj_MINIMAPPINGSTYLE_FLASHY = 1
export const bj_MINIMAPPINGSTYLE_ATTACK = 2
export const bj_CORPSE_MAX_DEATH_TIME = 8.00
export const bj_CORPSETYPE_FLESH = 0
export const bj_CORPSETYPE_BONE = 1
export const bj_ELEVATOR_BLOCKER_CODE = "DTep"
export const bj_ELEVATOR_CODE01 = "DTrf"
export const bj_ELEVATOR_CODE02 = "DTrx"
export const bj_ELEVATOR_WALL_TYPE_ALL = 0
export const bj_ELEVATOR_WALL_TYPE_EAST = 1
export const bj_ELEVATOR_WALL_TYPE_NORTH = 2
export const bj_ELEVATOR_WALL_TYPE_SOUTH = 3
export const bj_ELEVATOR_WALL_TYPE_WEST = 4
export const bj_MELEE_MAX_TWINKED_HEROES = 0
export const bj_mapInitialPlayableArea = null
export const bj_mapInitialCameraBounds = null
export const bj_forLoopAIndex = 0
export const bj_forLoopBIndex = 0
export const bj_forLoopAIndexEnd = 0
export const bj_forLoopBIndexEnd = 0
export const bj_slotControlReady = false
export const bj_gameStartedTimer = null
export const bj_gameStarted = false
export const bj_isSinglePlayer = false
export const bj_dncSoundsDay = null
export const bj_dncSoundsNight = null
export const bj_dayAmbientSound = null
export const bj_nightAmbientSound = null
export const bj_dncSoundsDawn = null
export const bj_dncSoundsDusk = null
export const bj_dawnSound = null
export const bj_duskSound = null
export const bj_useDawnDuskSounds = true
export const bj_dncIsDaytime = false
export const bj_rescueSound = null
export const bj_questDiscoveredSound = null
export const bj_questUpdatedSound = null
export const bj_questCompletedSound = null
export const bj_questFailedSound = null
export const bj_questHintSound = null
export const bj_questSecretSound = null
export const bj_questItemAcquiredSound = null
export const bj_questWarningSound = null
export const bj_victoryDialogSound = null
export const bj_defeatDialogSound = null
export const bj_rescueUnitBehavior = null
export const bj_rescueChangeColorUnit = true
export const bj_rescueChangeColorBldg = true
export const bj_cineSceneEndingTimer = null
export const bj_cineSceneLastSound = null
export const bj_cineSceneBeingSkipped = null
export const bj_cineModePriorSpeed = MAP_SPEED_NORMAL
export const bj_cineModePriorFogSetting = false
export const bj_cineModePriorMaskSetting = false
export const bj_cineModeAlreadyIn = false
export const bj_cineModePriorDawnDusk = false
export const bj_cineModeSavedSeed = 0
export const bj_cineFadeFinishTimer = null
export const bj_cineFadeContinueTimer = null
export const bj_cineFadeContinueRed = 0
export const bj_cineFadeContinueGreen = 0
export const bj_cineFadeContinueBlue = 0
export const bj_cineFadeContinueTrans = 0
export const bj_cineFadeContinueDuration = 0
export const bj_cineFadeContinueTex = ""
export const JASS_MAX_ARRAY_SIZE = 8192
export const PLAYER_NEUTRAL_PASSIVE = 15
export const PLAYER_NEUTRAL_AGGRESSIVE = 12
export const PLAYER_COLOR_RED = cj.ConvertPlayerColor(0)
export const PLAYER_COLOR_BLUE = cj.ConvertPlayerColor(1)
export const PLAYER_COLOR_CYAN = cj.ConvertPlayerColor(2)
export const PLAYER_COLOR_PURPLE = cj.ConvertPlayerColor(3)
export const PLAYER_COLOR_YELLOW = cj.ConvertPlayerColor(4)
export const PLAYER_COLOR_ORANGE = cj.ConvertPlayerColor(5)
export const PLAYER_COLOR_GREEN = cj.ConvertPlayerColor(6)
export const PLAYER_COLOR_PINK = cj.ConvertPlayerColor(7)
export const PLAYER_COLOR_LIGHT_GRAY = cj.ConvertPlayerColor(8)
export const PLAYER_COLOR_LIGHT_BLUE = cj.ConvertPlayerColor(9)
export const PLAYER_COLOR_AQUA = cj.ConvertPlayerColor(10)
export const PLAYER_COLOR_BROWN = cj.ConvertPlayerColor(11)
export const PLAYER_COLOR_BLACK = cj.ConvertPlayerColor(12)
export const RACE_HUMAN = cj.ConvertRace(1)
export const RACE_ORC = cj.ConvertRace(2)
export const RACE_UNDEAD = cj.ConvertRace(3)
export const RACE_NIGHTELF = cj.ConvertRace(4)
export const RACE_DEMON = cj.ConvertRace(5)
export const RACE_OTHER = cj.ConvertRace(7)
export const PLAYER_GAME_RESULT_VICTORY = cj.ConvertPlayerGameResult(0)
export const PLAYER_GAME_RESULT_DEFEAT = cj.ConvertPlayerGameResult(1)
export const PLAYER_GAME_RESULT_TIE = cj.ConvertPlayerGameResult(2)
export const PLAYER_GAME_RESULT_NEUTRAL = cj.ConvertPlayerGameResult(3)
export const ALLIANCE_PASSIVE = cj.ConvertAllianceType(0)
export const ALLIANCE_HELP_REQUEST = cj.ConvertAllianceType(1)
export const ALLIANCE_HELP_RESPONSE = cj.ConvertAllianceType(2)
export const ALLIANCE_SHARED_XP = cj.ConvertAllianceType(3)
export const ALLIANCE_SHARED_SPELLS = cj.ConvertAllianceType(4)
export const ALLIANCE_SHARED_VISION = cj.ConvertAllianceType(5)
export const ALLIANCE_SHARED_CONTROL = cj.ConvertAllianceType(6)
export const ALLIANCE_SHARED_ADVANCED_CONTROL = cj.ConvertAllianceType(7)
export const ALLIANCE_RESCUABLE = cj.ConvertAllianceType(8)
export const ALLIANCE_SHARED_VISION_FORCED = cj.ConvertAllianceType(9)
export const VERSION_REIGN_OF_CHAOS = cj.ConvertVersion(0)
export const VERSION_FROZEN_THRONE = cj.ConvertVersion(1)
export const ATTACK_TYPE_NORMAL = cj.ConvertAttackType(0)
export const ATTACK_TYPE_MELEE = cj.ConvertAttackType(1)
export const ATTACK_TYPE_PIERCE = cj.ConvertAttackType(2)
export const ATTACK_TYPE_SIEGE = cj.ConvertAttackType(3)
export const ATTACK_TYPE_MAGIC = cj.ConvertAttackType(4)
export const ATTACK_TYPE_CHAOS = cj.ConvertAttackType(5)
export const ATTACK_TYPE_HERO = cj.ConvertAttackType(6)
export const DAMAGE_TYPE_UNKNOWN = cj.ConvertDamageType(0)
export const DAMAGE_TYPE_NORMAL = cj.ConvertDamageType(4)
export const DAMAGE_TYPE_ENHANCED = cj.ConvertDamageType(5)
export const DAMAGE_TYPE_FIRE = cj.ConvertDamageType(8)
export const DAMAGE_TYPE_COLD = cj.ConvertDamageType(9)
export const DAMAGE_TYPE_LIGHTNING = cj.ConvertDamageType(10)
export const DAMAGE_TYPE_POISON = cj.ConvertDamageType(11)
export const DAMAGE_TYPE_DISEASE = cj.ConvertDamageType(12)
export const DAMAGE_TYPE_DIVINE = cj.ConvertDamageType(13)
export const DAMAGE_TYPE_MAGIC = cj.ConvertDamageType(14)
export const DAMAGE_TYPE_SONIC = cj.ConvertDamageType(15)
export const DAMAGE_TYPE_ACID = cj.ConvertDamageType(16)
export const DAMAGE_TYPE_FORCE = cj.ConvertDamageType(17)
export const DAMAGE_TYPE_DEATH = cj.ConvertDamageType(18)
export const DAMAGE_TYPE_MIND = cj.ConvertDamageType(19)
export const DAMAGE_TYPE_PLANT = cj.ConvertDamageType(20)
export const DAMAGE_TYPE_DEFENSIVE = cj.ConvertDamageType(21)
export const DAMAGE_TYPE_DEMOLITION = cj.ConvertDamageType(22)
export const DAMAGE_TYPE_SLOW_POISON = cj.ConvertDamageType(23)
export const DAMAGE_TYPE_SPIRIT_LINK = cj.ConvertDamageType(24)
export const DAMAGE_TYPE_SHADOW_STRIKE = cj.ConvertDamageType(25)
export const DAMAGE_TYPE_UNIVERSAL = cj.ConvertDamageType(26)
export const WEAPON_TYPE_WHOKNOWS = cj.ConvertWeaponType(0)
export const WEAPON_TYPE_METAL_LIGHT_CHOP = cj.ConvertWeaponType(1)
export const WEAPON_TYPE_METAL_MEDIUM_CHOP = cj.ConvertWeaponType(2)
export const WEAPON_TYPE_METAL_HEAVY_CHOP = cj.ConvertWeaponType(3)
export const WEAPON_TYPE_METAL_LIGHT_SLICE = cj.ConvertWeaponType(4)
export const WEAPON_TYPE_METAL_MEDIUM_SLICE = cj.ConvertWeaponType(5)
export const WEAPON_TYPE_METAL_HEAVY_SLICE = cj.ConvertWeaponType(6)
export const WEAPON_TYPE_METAL_MEDIUM_BASH = cj.ConvertWeaponType(7)
export const WEAPON_TYPE_METAL_HEAVY_BASH = cj.ConvertWeaponType(8)
export const WEAPON_TYPE_METAL_MEDIUM_STAB = cj.ConvertWeaponType(9)
export const WEAPON_TYPE_METAL_HEAVY_STAB = cj.ConvertWeaponType(10)
export const WEAPON_TYPE_WOOD_LIGHT_SLICE = cj.ConvertWeaponType(11)
export const WEAPON_TYPE_WOOD_MEDIUM_SLICE = cj.ConvertWeaponType(12)
export const WEAPON_TYPE_WOOD_HEAVY_SLICE = cj.ConvertWeaponType(13)
export const WEAPON_TYPE_WOOD_LIGHT_BASH = cj.ConvertWeaponType(14)
export const WEAPON_TYPE_WOOD_MEDIUM_BASH = cj.ConvertWeaponType(15)
export const WEAPON_TYPE_WOOD_HEAVY_BASH = cj.ConvertWeaponType(16)
export const WEAPON_TYPE_WOOD_LIGHT_STAB = cj.ConvertWeaponType(17)
export const WEAPON_TYPE_WOOD_MEDIUM_STAB = cj.ConvertWeaponType(18)
export const WEAPON_TYPE_CLAW_LIGHT_SLICE = cj.ConvertWeaponType(19)
export const WEAPON_TYPE_CLAW_MEDIUM_SLICE = cj.ConvertWeaponType(20)
export const WEAPON_TYPE_CLAW_HEAVY_SLICE = cj.ConvertWeaponType(21)
export const WEAPON_TYPE_AXE_MEDIUM_CHOP = cj.ConvertWeaponType(22)
export const WEAPON_TYPE_ROCK_HEAVY_BASH = cj.ConvertWeaponType(23)
export const PATHING_TYPE_ANY = cj.ConvertPathingType(0)
export const PATHING_TYPE_WALKABILITY = cj.ConvertPathingType(1)
export const PATHING_TYPE_FLYABILITY = cj.ConvertPathingType(2)
export const PATHING_TYPE_BUILDABILITY = cj.ConvertPathingType(3)
export const PATHING_TYPE_PEONHARVESTPATHING = cj.ConvertPathingType(4)
export const PATHING_TYPE_BLIGHTPATHING = cj.ConvertPathingType(5)
export const PATHING_TYPE_FLOATABILITY = cj.ConvertPathingType(6)
export const PATHING_TYPE_AMPHIBIOUSPATHING = cj.ConvertPathingType(7)
export const RACE_PREF_HUMAN = cj.ConvertRacePref(1)
export const RACE_PREF_ORC = cj.ConvertRacePref(2)
export const RACE_PREF_NIGHTELF = cj.ConvertRacePref(4)
export const RACE_PREF_UNDEAD = cj.ConvertRacePref(8)
export const RACE_PREF_DEMON = cj.ConvertRacePref(16)
export const RACE_PREF_RANDOM = cj.ConvertRacePref(32)
export const RACE_PREF_USER_SELECTABLE = cj.ConvertRacePref(64)
export const MAP_CONTROL_USER = cj.ConvertMapControl(0)
export const MAP_CONTROL_COMPUTER = cj.ConvertMapControl(1)
export const MAP_CONTROL_RESCUABLE = cj.ConvertMapControl(2)
export const MAP_CONTROL_NEUTRAL = cj.ConvertMapControl(3)
export const MAP_CONTROL_CREEP = cj.ConvertMapControl(4)
export const MAP_CONTROL_NONE = cj.ConvertMapControl(5)
export const GAME_TYPE_MELEE = cj.ConvertGameType(1)
export const GAME_TYPE_FFA = cj.ConvertGameType(2)
export const GAME_TYPE_USE_MAP_SETTINGS = cj.ConvertGameType(4)
export const GAME_TYPE_BLIZ = cj.ConvertGameType(8)
export const GAME_TYPE_ONE_ON_ONE = cj.ConvertGameType(16)
export const GAME_TYPE_TWO_TEAM_PLAY = cj.ConvertGameType(32)
export const GAME_TYPE_THREE_TEAM_PLAY = cj.ConvertGameType(64)
export const GAME_TYPE_FOUR_TEAM_PLAY = cj.ConvertGameType(128)
export const MAP_FOG_HIDE_TERRAIN = cj.ConvertMapFlag(1)
export const MAP_FOG_MAP_EXPLORED = cj.ConvertMapFlag(2)
export const MAP_FOG_ALWAYS_VISIBLE = cj.ConvertMapFlag(4)
export const MAP_USE_HANDICAPS = cj.ConvertMapFlag(8)
export const MAP_OBSERVERS = cj.ConvertMapFlag(16)
export const MAP_OBSERVERS_ON_DEATH = cj.ConvertMapFlag(32)
export const MAP_FIXED_COLORS = cj.ConvertMapFlag(128)
export const MAP_LOCK_RESOURCE_TRADING = cj.ConvertMapFlag(256)
export const MAP_RESOURCE_TRADING_ALLIES_ONLY = cj.ConvertMapFlag(512)
export const MAP_LOCK_ALLIANCE_CHANGES = cj.ConvertMapFlag(1024)
export const MAP_ALLIANCE_CHANGES_HIDDEN = cj.ConvertMapFlag(2048)
export const MAP_CHEATS = cj.ConvertMapFlag(4096)
export const MAP_CHEATS_HIDDEN = cj.ConvertMapFlag(8192)
export const MAP_LOCK_SPEED = cj.ConvertMapFlag(8192 * 2)
export const MAP_LOCK_RANDOM_SEED = cj.ConvertMapFlag(8192 * 4)
export const MAP_SHARED_ADVANCED_CONTROL = cj.ConvertMapFlag(8192 * 8)
export const MAP_RANDOM_HERO = cj.ConvertMapFlag(8192 * 16)
export const MAP_RANDOM_RACES = cj.ConvertMapFlag(8192 * 32)
export const MAP_RELOADED = cj.ConvertMapFlag(8192 * 64)
export const MAP_PLACEMENT_RANDOM = cj.ConvertPlacement(0)
export const MAP_PLACEMENT_FIXED = cj.ConvertPlacement(1)
export const MAP_PLACEMENT_USE_MAP_SETTINGS = cj.ConvertPlacement(2)
export const MAP_PLACEMENT_TEAMS_TOGETHER = cj.ConvertPlacement(3)
export const MAP_LOC_PRIO_LOW = cj.ConvertStartLocPrio(0)
export const MAP_LOC_PRIO_HIGH = cj.ConvertStartLocPrio(1)
export const MAP_LOC_PRIO_NOT = cj.ConvertStartLocPrio(2)
export const MAP_DENSITY_NONE = cj.ConvertMapDensity(0)
export const MAP_DENSITY_LIGHT = cj.ConvertMapDensity(1)
export const MAP_DENSITY_MEDIUM = cj.ConvertMapDensity(2)
export const MAP_DENSITY_HEAVY = cj.ConvertMapDensity(3)
export const MAP_DIFFICULTY_EASY = cj.ConvertGameDifficulty(0)
export const MAP_DIFFICULTY_NORMAL = cj.ConvertGameDifficulty(1)
export const MAP_DIFFICULTY_HARD = cj.ConvertGameDifficulty(2)
export const MAP_DIFFICULTY_INSANE = cj.ConvertGameDifficulty(3)
export const MAP_SPEED_SLOWEST = cj.ConvertGameSpeed(0)
export const MAP_SPEED_SLOW = cj.ConvertGameSpeed(1)
// export const MAP_SPEED_NORMAL = cj.ConvertGameSpeed(2)
export const MAP_SPEED_FAST = cj.ConvertGameSpeed(3)
export const MAP_SPEED_FASTEST = cj.ConvertGameSpeed(4)
export const PLAYER_SLOT_STATE_EMPTY = cj.ConvertPlayerSlotState(0)
export const PLAYER_SLOT_STATE_PLAYING = cj.ConvertPlayerSlotState(1)
export const PLAYER_SLOT_STATE_LEFT = cj.ConvertPlayerSlotState(2)
export const SOUND_VOLUMEGROUP_UNITMOVEMENT = cj.ConvertVolumeGroup(0)
export const SOUND_VOLUMEGROUP_UNITSOUNDS = cj.ConvertVolumeGroup(1)
export const SOUND_VOLUMEGROUP_COMBAT = cj.ConvertVolumeGroup(2)
export const SOUND_VOLUMEGROUP_SPELLS = cj.ConvertVolumeGroup(3)
export const SOUND_VOLUMEGROUP_UI = cj.ConvertVolumeGroup(4)
export const SOUND_VOLUMEGROUP_MUSIC = cj.ConvertVolumeGroup(5)
export const SOUND_VOLUMEGROUP_AMBIENTSOUNDS = cj.ConvertVolumeGroup(6)
export const SOUND_VOLUMEGROUP_FIRE = cj.ConvertVolumeGroup(7)
export const GAME_STATE_DIVINE_INTERVENTION = cj.ConvertIGameState(0)
export const GAME_STATE_DISCONNECTED = cj.ConvertIGameState(1)
export const GAME_STATE_TIME_OF_DAY = cj.ConvertFGameState(2)
export const PLAYER_STATE_GAME_RESULT = cj.ConvertPlayerState(0)
export const PLAYER_STATE_RESOURCE_GOLD = cj.ConvertPlayerState(1)
export const PLAYER_STATE_RESOURCE_LUMBER = cj.ConvertPlayerState(2)
export const PLAYER_STATE_RESOURCE_HERO_TOKENS = cj.ConvertPlayerState(3)
export const PLAYER_STATE_RESOURCE_FOOD_CAP = cj.ConvertPlayerState(4)
export const PLAYER_STATE_RESOURCE_FOOD_USED = cj.ConvertPlayerState(5)
export const PLAYER_STATE_FOOD_CAP_CEILING = cj.ConvertPlayerState(6)
export const PLAYER_STATE_GIVES_BOUNTY = cj.ConvertPlayerState(7)
export const PLAYER_STATE_ALLIED_VICTORY = cj.ConvertPlayerState(8)
export const PLAYER_STATE_PLACED = cj.ConvertPlayerState(9)
export const PLAYER_STATE_OBSERVER_ON_DEATH = cj.ConvertPlayerState(10)
export const PLAYER_STATE_OBSERVER = cj.ConvertPlayerState(11)
export const PLAYER_STATE_UNFOLLOWABLE = cj.ConvertPlayerState(12)
export const PLAYER_STATE_GOLD_UPKEEP_RATE = cj.ConvertPlayerState(13)
export const PLAYER_STATE_LUMBER_UPKEEP_RATE = cj.ConvertPlayerState(14)
export const PLAYER_STATE_GOLD_GATHERED = cj.ConvertPlayerState(15)
export const PLAYER_STATE_LUMBER_GATHERED = cj.ConvertPlayerState(16)
export const PLAYER_STATE_NO_CREEP_SLEEP = cj.ConvertPlayerState(25)
export const UNIT_STATE_LIFE = cj.ConvertUnitState(0)
export const UNIT_STATE_MAX_LIFE = cj.ConvertUnitState(1)
export const UNIT_STATE_MANA = cj.ConvertUnitState(2)
export const UNIT_STATE_MAX_MANA = cj.ConvertUnitState(3)
export const UNIT_STATE_ATTACK_DICE = cj.ConvertUnitState(0x10)
export const UNIT_STATE_ATTACK_SIDE = cj.ConvertUnitState(0x11)
export const UNIT_STATE_ATTACK_WHITE = cj.ConvertUnitState(0x12)
export const UNIT_STATE_ATTACK_BONUS = cj.ConvertUnitState(0x13)
export const UNIT_STATE_ATTACK_MIX = cj.ConvertUnitState(0x14)
export const UNIT_STATE_ATTACK_MAX = cj.ConvertUnitState(0x15)
export const UNIT_STATE_ATTACK_RANGE = cj.ConvertUnitState(0x16)
export const UNIT_STATE_DEFEND_WHITE = cj.ConvertUnitState(0x20)
export const UNIT_STATE_ATTACK_SPACE = cj.ConvertUnitState(0x25)
export const UNIT_STATE_ATTACK_SPEED = cj.ConvertUnitState(0x51)
export const AI_DIFFICULTY_NEWBIE = cj.ConvertAIDifficulty(0)
export const AI_DIFFICULTY_NORMAL = cj.ConvertAIDifficulty(1)
export const AI_DIFFICULTY_INSANE = cj.ConvertAIDifficulty(2)
export const PLAYER_SCORE_UNITS_TRAINED = cj.ConvertPlayerScore(0)
export const PLAYER_SCORE_UNITS_KILLED = cj.ConvertPlayerScore(1)
export const PLAYER_SCORE_STRUCT_BUILT = cj.ConvertPlayerScore(2)
export const PLAYER_SCORE_STRUCT_RAZED = cj.ConvertPlayerScore(3)
export const PLAYER_SCORE_TECH_PERCENT = cj.ConvertPlayerScore(4)
export const PLAYER_SCORE_FOOD_MAXPROD = cj.ConvertPlayerScore(5)
export const PLAYER_SCORE_FOOD_MAXUSED = cj.ConvertPlayerScore(6)
export const PLAYER_SCORE_HEROES_KILLED = cj.ConvertPlayerScore(7)
export const PLAYER_SCORE_ITEMS_GAINED = cj.ConvertPlayerScore(8)
export const PLAYER_SCORE_MERCS_HIRED = cj.ConvertPlayerScore(9)
export const PLAYER_SCORE_GOLD_MINED_TOTAL = cj.ConvertPlayerScore(10)
export const PLAYER_SCORE_GOLD_MINED_UPKEEP = cj.ConvertPlayerScore(11)
export const PLAYER_SCORE_GOLD_LOST_UPKEEP = cj.ConvertPlayerScore(12)
export const PLAYER_SCORE_GOLD_LOST_TAX = cj.ConvertPlayerScore(13)
export const PLAYER_SCORE_GOLD_GIVEN = cj.ConvertPlayerScore(14)
export const PLAYER_SCORE_GOLD_RECEIVED = cj.ConvertPlayerScore(15)
export const PLAYER_SCORE_LUMBER_TOTAL = cj.ConvertPlayerScore(16)
export const PLAYER_SCORE_LUMBER_LOST_UPKEEP = cj.ConvertPlayerScore(17)
export const PLAYER_SCORE_LUMBER_LOST_TAX = cj.ConvertPlayerScore(18)
export const PLAYER_SCORE_LUMBER_GIVEN = cj.ConvertPlayerScore(19)
export const PLAYER_SCORE_LUMBER_RECEIVED = cj.ConvertPlayerScore(20)
export const PLAYER_SCORE_UNIT_TOTAL = cj.ConvertPlayerScore(21)
export const PLAYER_SCORE_HERO_TOTAL = cj.ConvertPlayerScore(22)
export const PLAYER_SCORE_RESOURCE_TOTAL = cj.ConvertPlayerScore(23)
export const PLAYER_SCORE_TOTAL = cj.ConvertPlayerScore(24)
export const EVENT_GAME_VICTORY = cj.ConvertGameEvent(0)
export const EVENT_GAME_END_LEVEL = cj.ConvertGameEvent(1)
export const EVENT_GAME_VARIABLE_LIMIT = cj.ConvertGameEvent(2)
export const EVENT_GAME_STATE_LIMIT = cj.ConvertGameEvent(3)
export const EVENT_GAME_TIMER_EXPIRED = cj.ConvertGameEvent(4)
export const EVENT_GAME_ENTER_REGION = cj.ConvertGameEvent(5)
export const EVENT_GAME_LEAVE_REGION = cj.ConvertGameEvent(6)
export const EVENT_GAME_TRACKABLE_HIT = cj.ConvertGameEvent(7)
export const EVENT_GAME_TRACKABLE_TRACK = cj.ConvertGameEvent(8)
export const EVENT_GAME_SHOW_SKILL = cj.ConvertGameEvent(9)
export const EVENT_GAME_BUILD_SUBMENU = cj.ConvertGameEvent(10)
export const EVENT_PLAYER_STATE_LIMIT = cj.ConvertPlayerEvent(11)
export const EVENT_PLAYER_ALLIANCE_CHANGED = cj.ConvertPlayerEvent(12)
export const EVENT_PLAYER_DEFEAT = cj.ConvertPlayerEvent(13)
export const EVENT_PLAYER_VICTORY = cj.ConvertPlayerEvent(14)
export const EVENT_PLAYER_LEAVE = cj.ConvertPlayerEvent(15)
export const EVENT_PLAYER_CHAT = cj.ConvertPlayerEvent(16)
export const EVENT_PLAYER_END_CINEMATIC = cj.ConvertPlayerEvent(17)
export const EVENT_PLAYER_UNIT_ATTACKED = cj.ConvertPlayerUnitEvent(18)
export const EVENT_PLAYER_UNIT_RESCUED = cj.ConvertPlayerUnitEvent(19)
export const EVENT_PLAYER_UNIT_DEATH = cj.ConvertPlayerUnitEvent(20)
export const EVENT_PLAYER_UNIT_DECAY = cj.ConvertPlayerUnitEvent(21)
export const EVENT_PLAYER_UNIT_DETECTED = cj.ConvertPlayerUnitEvent(22)
export const EVENT_PLAYER_UNIT_HIDDEN = cj.ConvertPlayerUnitEvent(23)
export const EVENT_PLAYER_UNIT_SELECTED = cj.ConvertPlayerUnitEvent(24)
export const EVENT_PLAYER_UNIT_DESELECTED = cj.ConvertPlayerUnitEvent(25)
export const EVENT_PLAYER_UNIT_CONSTRUCT_START = cj.ConvertPlayerUnitEvent(26)
export const EVENT_PLAYER_UNIT_CONSTRUCT_CANCEL = cj.ConvertPlayerUnitEvent(27)
export const EVENT_PLAYER_UNIT_CONSTRUCT_FINISH = cj.ConvertPlayerUnitEvent(28)
export const EVENT_PLAYER_UNIT_UPGRADE_START = cj.ConvertPlayerUnitEvent(29)
export const EVENT_PLAYER_UNIT_UPGRADE_CANCEL = cj.ConvertPlayerUnitEvent(30)
export const EVENT_PLAYER_UNIT_UPGRADE_FINISH = cj.ConvertPlayerUnitEvent(31)
export const EVENT_PLAYER_UNIT_TRAIN_START = cj.ConvertPlayerUnitEvent(32)
export const EVENT_PLAYER_UNIT_TRAIN_CANCEL = cj.ConvertPlayerUnitEvent(33)
export const EVENT_PLAYER_UNIT_TRAIN_FINISH = cj.ConvertPlayerUnitEvent(34)
export const EVENT_PLAYER_UNIT_RESEARCH_START = cj.ConvertPlayerUnitEvent(35)
export const EVENT_PLAYER_UNIT_RESEARCH_CANCEL = cj.ConvertPlayerUnitEvent(36)
export const EVENT_PLAYER_UNIT_RESEARCH_FINISH = cj.ConvertPlayerUnitEvent(37)
export const EVENT_PLAYER_UNIT_ISSUED_ORDER = cj.ConvertPlayerUnitEvent(38)
export const EVENT_PLAYER_UNIT_ISSUED_POINT_ORDER = cj.ConvertPlayerUnitEvent(39)
export const EVENT_PLAYER_UNIT_ISSUED_TARGET_ORDER = cj.ConvertPlayerUnitEvent(40)
export const EVENT_PLAYER_UNIT_ISSUED_UNIT_ORDER = cj.ConvertPlayerUnitEvent(40)
export const EVENT_PLAYER_HERO_LEVEL = cj.ConvertPlayerUnitEvent(41)
export const EVENT_PLAYER_HERO_SKILL = cj.ConvertPlayerUnitEvent(42)
export const EVENT_PLAYER_HERO_REVIVABLE = cj.ConvertPlayerUnitEvent(43)
export const EVENT_PLAYER_HERO_REVIVE_START = cj.ConvertPlayerUnitEvent(44)
export const EVENT_PLAYER_HERO_REVIVE_CANCEL = cj.ConvertPlayerUnitEvent(45)
export const EVENT_PLAYER_HERO_REVIVE_FINISH = cj.ConvertPlayerUnitEvent(46)
export const EVENT_PLAYER_UNIT_SUMMON = cj.ConvertPlayerUnitEvent(47)
export const EVENT_PLAYER_UNIT_DROP_ITEM = cj.ConvertPlayerUnitEvent(48)
export const EVENT_PLAYER_UNIT_PICKUP_ITEM = cj.ConvertPlayerUnitEvent(49)
export const EVENT_PLAYER_UNIT_USE_ITEM = cj.ConvertPlayerUnitEvent(50)
export const EVENT_PLAYER_UNIT_LOADED = cj.ConvertPlayerUnitEvent(51)
export const EVENT_UNIT_DAMAGED = cj.ConvertUnitEvent(52)
export const EVENT_UNIT_DEATH = cj.ConvertUnitEvent(53)
export const EVENT_UNIT_DECAY = cj.ConvertUnitEvent(54)
export const EVENT_UNIT_DETECTED = cj.ConvertUnitEvent(55)
export const EVENT_UNIT_HIDDEN = cj.ConvertUnitEvent(56)
export const EVENT_UNIT_SELECTED = cj.ConvertUnitEvent(57)
export const EVENT_UNIT_DESELECTED = cj.ConvertUnitEvent(58)
export const EVENT_UNIT_STATE_LIMIT = cj.ConvertUnitEvent(59)
export const EVENT_UNIT_ACQUIRED_TARGET = cj.ConvertUnitEvent(60)
export const EVENT_UNIT_TARGET_IN_RANGE = cj.ConvertUnitEvent(61)
export const EVENT_UNIT_ATTACKED = cj.ConvertUnitEvent(62)
export const EVENT_UNIT_RESCUED = cj.ConvertUnitEvent(63)
export const EVENT_UNIT_CONSTRUCT_CANCEL = cj.ConvertUnitEvent(64)
export const EVENT_UNIT_CONSTRUCT_FINISH = cj.ConvertUnitEvent(65)
export const EVENT_UNIT_UPGRADE_START = cj.ConvertUnitEvent(66)
export const EVENT_UNIT_UPGRADE_CANCEL = cj.ConvertUnitEvent(67)
export const EVENT_UNIT_UPGRADE_FINISH = cj.ConvertUnitEvent(68)
export const EVENT_UNIT_TRAIN_START = cj.ConvertUnitEvent(69)
export const EVENT_UNIT_TRAIN_CANCEL = cj.ConvertUnitEvent(70)
export const EVENT_UNIT_TRAIN_FINISH = cj.ConvertUnitEvent(71)
export const EVENT_UNIT_RESEARCH_START = cj.ConvertUnitEvent(72)
export const EVENT_UNIT_RESEARCH_CANCEL = cj.ConvertUnitEvent(73)
export const EVENT_UNIT_RESEARCH_FINISH = cj.ConvertUnitEvent(74)
export const EVENT_UNIT_ISSUED_ORDER = cj.ConvertUnitEvent(75)
export const EVENT_UNIT_ISSUED_POINT_ORDER = cj.ConvertUnitEvent(76)
export const EVENT_UNIT_ISSUED_TARGET_ORDER = cj.ConvertUnitEvent(77)
export const EVENT_UNIT_HERO_LEVEL = cj.ConvertUnitEvent(78)
export const EVENT_UNIT_HERO_SKILL = cj.ConvertUnitEvent(79)
export const EVENT_UNIT_HERO_REVIVABLE = cj.ConvertUnitEvent(80)
export const EVENT_UNIT_HERO_REVIVE_START = cj.ConvertUnitEvent(81)
export const EVENT_UNIT_HERO_REVIVE_CANCEL = cj.ConvertUnitEvent(82)
export const EVENT_UNIT_HERO_REVIVE_FINISH = cj.ConvertUnitEvent(83)
export const EVENT_UNIT_SUMMON = cj.ConvertUnitEvent(84)
export const EVENT_UNIT_DROP_ITEM = cj.ConvertUnitEvent(85)
export const EVENT_UNIT_PICKUP_ITEM = cj.ConvertUnitEvent(86)
export const EVENT_UNIT_USE_ITEM = cj.ConvertUnitEvent(87)
export const EVENT_UNIT_LOADED = cj.ConvertUnitEvent(88)
export const EVENT_WIDGET_DEATH = cj.ConvertWidgetEvent(89)
export const EVENT_DIALOG_BUTTON_CLICK = cj.ConvertDialogEvent(90)
export const EVENT_DIALOG_CLICK = cj.ConvertDialogEvent(91)
export const EVENT_GAME_LOADED = cj.ConvertGameEvent(256)
export const EVENT_GAME_TOURNAMENT_FINISH_SOON = cj.ConvertGameEvent(257)
export const EVENT_GAME_TOURNAMENT_FINISH_NOW = cj.ConvertGameEvent(258)
export const EVENT_GAME_SAVE = cj.ConvertGameEvent(259)
export const EVENT_PLAYER_ARROW_LEFT_DOWN = cj.ConvertPlayerEvent(261)
export const EVENT_PLAYER_ARROW_LEFT_UP = cj.ConvertPlayerEvent(262)
export const EVENT_PLAYER_ARROW_RIGHT_DOWN = cj.ConvertPlayerEvent(263)
export const EVENT_PLAYER_ARROW_RIGHT_UP = cj.ConvertPlayerEvent(264)
export const EVENT_PLAYER_ARROW_DOWN_DOWN = cj.ConvertPlayerEvent(265)
export const EVENT_PLAYER_ARROW_DOWN_UP = cj.ConvertPlayerEvent(266)
export const EVENT_PLAYER_ARROW_UP_DOWN = cj.ConvertPlayerEvent(267)
export const EVENT_PLAYER_ARROW_UP_UP = cj.ConvertPlayerEvent(268)
export const EVENT_PLAYER_UNIT_SELL = cj.ConvertPlayerUnitEvent(269)
export const EVENT_PLAYER_UNIT_CHANGE_OWNER = cj.ConvertPlayerUnitEvent(270)
export const EVENT_PLAYER_UNIT_SELL_ITEM = cj.ConvertPlayerUnitEvent(271)
export const EVENT_PLAYER_UNIT_SPELL_CHANNEL = cj.ConvertPlayerUnitEvent(272)
export const EVENT_PLAYER_UNIT_SPELL_CAST = cj.ConvertPlayerUnitEvent(273)
export const EVENT_PLAYER_UNIT_SPELL_EFFECT = cj.ConvertPlayerUnitEvent(274)
export const EVENT_PLAYER_UNIT_SPELL_FINISH = cj.ConvertPlayerUnitEvent(275)
export const EVENT_PLAYER_UNIT_SPELL_ENDCAST = cj.ConvertPlayerUnitEvent(276)
export const EVENT_PLAYER_UNIT_PAWN_ITEM = cj.ConvertPlayerUnitEvent(277)
export const EVENT_UNIT_SELL = cj.ConvertUnitEvent(286)
export const EVENT_UNIT_CHANGE_OWNER = cj.ConvertUnitEvent(287)
export const EVENT_UNIT_SELL_ITEM = cj.ConvertUnitEvent(288)
export const EVENT_UNIT_SPELL_CHANNEL = cj.ConvertUnitEvent(289)
export const EVENT_UNIT_SPELL_CAST = cj.ConvertUnitEvent(290)
export const EVENT_UNIT_SPELL_EFFECT = cj.ConvertUnitEvent(291)
export const EVENT_UNIT_SPELL_FINISH = cj.ConvertUnitEvent(292)
export const EVENT_UNIT_SPELL_ENDCAST = cj.ConvertUnitEvent(293)
export const EVENT_UNIT_PAWN_ITEM = cj.ConvertUnitEvent(294)
export const LESS_THAN = cj.ConvertLimitOp(0)
export const LESS_THAN_OR_EQUAL = cj.ConvertLimitOp(1)
export const EQUAL = cj.ConvertLimitOp(2)
export const GREATER_THAN_OR_EQUAL = cj.ConvertLimitOp(3)
export const GREATER_THAN = cj.ConvertLimitOp(4)
export const NOT_EQUAL = cj.ConvertLimitOp(5)
export const UNIT_TYPE_HERO = cj.ConvertUnitType(0)
export const UNIT_TYPE_DEAD = cj.ConvertUnitType(1)
export const UNIT_TYPE_STRUCTURE = cj.ConvertUnitType(2)
export const UNIT_TYPE_FLYING = cj.ConvertUnitType(3)
export const UNIT_TYPE_GROUND = cj.ConvertUnitType(4)
export const UNIT_TYPE_ATTACKS_FLYING = cj.ConvertUnitType(5)
export const UNIT_TYPE_ATTACKS_GROUND = cj.ConvertUnitType(6)
export const UNIT_TYPE_MELEE_ATTACKER = cj.ConvertUnitType(7)
export const UNIT_TYPE_RANGED_ATTACKER = cj.ConvertUnitType(8)
export const UNIT_TYPE_GIANT = cj.ConvertUnitType(9)
export const UNIT_TYPE_SUMMONED = cj.ConvertUnitType(10)
export const UNIT_TYPE_STUNNED = cj.ConvertUnitType(11)
export const UNIT_TYPE_PLAGUED = cj.ConvertUnitType(12)
export const UNIT_TYPE_SNARED = cj.ConvertUnitType(13)
export const UNIT_TYPE_UNDEAD = cj.ConvertUnitType(14)
export const UNIT_TYPE_MECHANICAL = cj.ConvertUnitType(15)
export const UNIT_TYPE_PEON = cj.ConvertUnitType(16)
export const UNIT_TYPE_SAPPER = cj.ConvertUnitType(17)
export const UNIT_TYPE_TOWNHALL = cj.ConvertUnitType(18)
export const UNIT_TYPE_ANCIENT = cj.ConvertUnitType(19)
export const UNIT_TYPE_TAUREN = cj.ConvertUnitType(20)
export const UNIT_TYPE_POISONED = cj.ConvertUnitType(21)
export const UNIT_TYPE_POLYMORPHED = cj.ConvertUnitType(22)
export const UNIT_TYPE_SLEEPING = cj.ConvertUnitType(23)
export const UNIT_TYPE_RESISTANT = cj.ConvertUnitType(24)
export const UNIT_TYPE_ETHEREAL = cj.ConvertUnitType(25)
export const UNIT_TYPE_MAGIC_IMMUNE = cj.ConvertUnitType(26)
export const ITEM_TYPE_PERMANENT = cj.ConvertItemType(0)
export const ITEM_TYPE_CHARGED = cj.ConvertItemType(1)
export const ITEM_TYPE_POWERUP = cj.ConvertItemType(2)
export const ITEM_TYPE_ARTIFACT = cj.ConvertItemType(3)
export const ITEM_TYPE_PURCHASABLE = cj.ConvertItemType(4)
export const ITEM_TYPE_CAMPAIGN = cj.ConvertItemType(5)
export const ITEM_TYPE_MISCELLANEOUS = cj.ConvertItemType(6)
export const ITEM_TYPE_UNKNOWN = cj.ConvertItemType(7)
export const ITEM_TYPE_ANY = cj.ConvertItemType(8)
export const ITEM_TYPE_TOME = cj.ConvertItemType(2)
export const CAMERA_FIELD_TARGET_DISTANCE = cj.ConvertCameraField(0)
export const CAMERA_FIELD_FARZ = cj.ConvertCameraField(1)
export const CAMERA_FIELD_ANGLE_OF_ATTACK = cj.ConvertCameraField(2)
export const CAMERA_FIELD_FIELD_OF_VIEW = cj.ConvertCameraField(3)
export const CAMERA_FIELD_ROLL = cj.ConvertCameraField(4)
export const CAMERA_FIELD_ROTATION = cj.ConvertCameraField(5)
export const CAMERA_FIELD_ZOFFSET = cj.ConvertCameraField(6)
export const BLEND_MODE_NONE = cj.ConvertBlendMode(0)
export const BLEND_MODE_DONT_CARE = cj.ConvertBlendMode(0)
export const BLEND_MODE_KEYALPHA = cj.ConvertBlendMode(1)
export const BLEND_MODE_BLEND = cj.ConvertBlendMode(2)
export const BLEND_MODE_ADDITIVE = cj.ConvertBlendMode(3)
export const BLEND_MODE_MODULATE = cj.ConvertBlendMode(4)
export const BLEND_MODE_MODULATE_2X = cj.ConvertBlendMode(5)
export const RARITY_FREQUENT = cj.ConvertRarityControl(0)
export const RARITY_RARE = cj.ConvertRarityControl(1)
export const TEXMAP_FLAG_NONE = cj.ConvertTexMapFlags(0)
export const TEXMAP_FLAG_WRAP_U = cj.ConvertTexMapFlags(1)
export const TEXMAP_FLAG_WRAP_V = cj.ConvertTexMapFlags(2)
export const TEXMAP_FLAG_WRAP_UV = cj.ConvertTexMapFlags(3)
export const FOG_OF_WAR_MASKED = cj.ConvertFogState(1)
export const FOG_OF_WAR_FOGGED = cj.ConvertFogState(2)
export const FOG_OF_WAR_VISIBLE = cj.ConvertFogState(4)
export const CAMERA_MARGIN_LEFT = 0
export const CAMERA_MARGIN_RIGHT = 1
export const CAMERA_MARGIN_TOP = 2
export const CAMERA_MARGIN_BOTTOM = 3
export const EFFECT_TYPE_EFFECT = cj.ConvertEffectType(0)
export const EFFECT_TYPE_TARGET = cj.ConvertEffectType(1)
export const EFFECT_TYPE_CASTER = cj.ConvertEffectType(2)
export const EFFECT_TYPE_SPECIAL = cj.ConvertEffectType(3)
export const EFFECT_TYPE_AREA_EFFECT = cj.ConvertEffectType(4)
export const EFFECT_TYPE_MISSILE = cj.ConvertEffectType(5)
export const EFFECT_TYPE_LIGHTNING = cj.ConvertEffectType(6)
export const SOUND_TYPE_EFFECT = cj.ConvertSoundType(0)
export const SOUND_TYPE_EFFECT_LOOPED = cj.ConvertSoundType(1)
export const EVENT_DAMAGE_DATA_VAILD = 0
export const EVENT_DAMAGE_DATA_IS_PHYSICAL = 1
export const EVENT_DAMAGE_DATA_IS_ATTACK = 2
export const EVENT_DAMAGE_DATA_IS_RANGED = 3
export const EVENT_DAMAGE_DATA_DAMAGE_TYPE = 4
export const EVENT_DAMAGE_DATA_WEAPON_TYPE = 5
export const EVENT_DAMAGE_DATA_ATTACK_TYPE = 6
export const MOVE_TYPE_NONE = 0x00
export const MOVE_TYPE_NOT = 0x01
export const MOVE_TYPE_FOOT = 0x02
export const MOVE_TYPE_FLY = 0x04
export const MOVE_TYPE_MINE = 0x08
export const MOVE_TYPE_WIND = 0x10
export const MOVE_TYPE_UN = 0x20
export const MOVE_TYPE_FLOAT = 0x40
export const MOVE_TYPE_AMPH = 0x80
export const COLLISION_TYPE_UNIT = 1
export const COLLISION_TYPE_BUILDING = 3
export const FRAME_ALIGN_LEFT_TOP = 0
export const FRAME_ALIGN_TOP = 1
export const FRAME_ALIGN_RIGHT_TOP = 2
export const FRAME_ALIGN_LEFT = 3
export const FRAME_ALIGN_CENTER = 4
export const FRAME_ALIGN_RIGHT = 5
export const FRAME_ALIGN_LEFT_BOTTOM = 6
export const FRAME_ALIGN_BOTTOM = 7
export const FRAME_ALIGN_RIGHT_BOTTOM = 8
export const MOUSE_ORDER_CLICK = 1
export const MOUSE_ORDER_ENTER = 2
export const MOUSE_ORDER_LEAVE = 3
export const MOUSE_ORDER_RELEASE = 4
export const MOUSE_ORDER_SCROLL = 6
export const MOUSE_ORDER_DOUBLE_CLICK = 12
export const GAME_KEY_MOUSE_LEFT = 1
export const GAME_KEY_MOUSE_RIGHT = 2
export const GAME_KEY_A = 65
export const GAME_KEY_B = 66
export const GAME_KEY_C = 67
export const GAME_KEY_D = 68
export const GAME_KEY_E = 69
export const GAME_KEY_F = 70
export const GAME_KEY_G = 71
export const GAME_KEY_H = 72
export const GAME_KEY_I = 73
export const GAME_KEY_J = 74
export const GAME_KEY_K = 75
export const GAME_KEY_L = 76
export const GAME_KEY_M = 77
export const GAME_KEY_N = 78
export const GAME_KEY_O = 79
export const GAME_KEY_P = 80
export const GAME_KEY_Q = 81
export const GAME_KEY_R = 82
export const GAME_KEY_S = 83
export const GAME_KEY_T = 84
export const GAME_KEY_U = 85
export const GAME_KEY_V = 86
export const GAME_KEY_W = 87
export const GAME_KEY_X = 88
export const GAME_KEY_Y = 89
export const GAME_KEY_Z = 90
export const GAME_KEY_0 = 48
export const GAME_KEY_1 = 49
export const GAME_KEY_2 = 50
export const GAME_KEY_3 = 51
export const GAME_KEY_4 = 52
export const GAME_KEY_5 = 53
export const GAME_KEY_6 = 53
export const GAME_KEY_7 = 55
export const GAME_KEY_8 = 56
export const GAME_KEY_9 = 57
export const GAME_KEY_TAB = 9
export const GAME_KEY_SPACE = 32
export const GAME_KEY_ENTER = 513
export const GAME_KEY_BACKSPACE = 514
export const GAME_KEY_SHIFT = 0
export const GAME_KEY_RIGHT = 516
export const GAME_KEY_UP = 517
export const GAME_KEY_LEFT = 518
export const GAME_KEY_DOWN = 519
export const GAME_KEY_ACTION_PRESS = 1
export const GAME_KEY_ACTION_RELEASE = 0
export const TEXT_ALIGN_LEFT_TOP = 11
export const TEXT_ALIGN_TOP = 17
export const TEXT_ALIGN_RIGHT_TOP = 37
export const TEXT_ALIGN_CENTER = 18
export const TEXT_ALIGN_LEFT = 10
export const TEXT_ALIGN_RIGHT = 34
export const TEXT_ALIGN_LEFT_BOTTOM = 12
export const TEXT_ALIGN_BOTTOM = 20
export const TEXT_ALIGN_RIGHT_BOTTOM = 36
